name: Lint, Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  main:
    timeout-minutes: 20
    name: Lint & Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Code Lint
        run: poetry run poe lint
      - name: Type check task with mypy
        run: poetry run poe type-check -- -- --show-error-context --pretty
      - name: Code Format
        run: poetry run poe format
      - name: Build
        run: poetry build
