name: Lint, Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  main:
    timeout-minutes: 10
    name: Lint & Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --locked --dev

      - name: Code Lint
        run: uv run poe lint

      - name: Type check task with mypy
        run: uv run poe type-check -- --show-error-context --pretty

      - name: Code Format
        run: uv run poe format

      - name: Build
        run: uv build
